name: Kiuwan

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    scan:
        uses: TransbankDevelopers/transbank-github-actions-templates/.github/workflows/kiuwan-pr-scan.yml@02f92d3b1c1b56c6242aa7c76eb9479fd82187aa
        with:
            project_name: td-webpay-sdk-python
            source_path: .
            fail_on_audit: true
        secrets:
            VPN_CONFIG_B64: ${{ secrets.VPN_CONFIG_B64 }}
            VPN_USER: ${{ secrets.VPN_USER }}
            VPN_PASS: ${{ secrets.VPN_PASS }}
            KIUWAN_USER: ${{ secrets.KIUWAN_USER }}
            KIUWAN_PASS: ${{ secrets.KIUWAN_PASS }}
