name: Publish Python Package to PyPI

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: pip

            - name: Install pipenv
              run: |
                  python -m pip install --upgrade pip
                  pip install pipenv

            - name: Install dependencies
              run: pipenv install --dev

            - name: Install build tools
              run: pipenv install build twine wheel

            - name: Build package
              run: pipenv run python -m build --sdist --wheel

            - name: Verify distribution files
              run: pipenv run twine check dist/*

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://upload.pypi.org/legacy/
