name: Sonar Scan
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    sonarqube:
        name: SonarQube
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v5
            - name: Install tox
              run: |
                  pip install tox
            - name: Run Tox
              run: |
                  tox -e cov
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
