name: Sonar Scan
on:
    pull_request:
        types: [opened, synchronize, reopened]
permissions:
    contents: read
    pull-requests: read
jobs:
    sonarqube:
        name: SonarQube
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
            - name: Install tox
              run: |
                  pip install tox
            - name: Run Tox
              run: |
                  tox -e cov
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
